name: autotests

on:
  pull_request:
  push:
  workflow_dispatch:

permissions:
  checks: write
  contents: read
  pull-requests: write
  issues: read

jobs:
  sprint_1_map_json:
    if: github.repository_owner != 'cpppracticum'
    runs-on: ubuntu-22.04
    steps:

      - name: Checkout code & tests
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install dependencies
        run: |
          pip uninstall conan -y
          pip install -U conan==1.59.0

      - name: Configure Conan profile for C++11 ABI
        run: |
          conan profile detect --force
          conan profile update settings.compiler.libcxx=libstdc++11 default

      - name: Build map_json binary with Conan
        run: |
          cd cpp-backend-tests-practicum/scripts/sprint1/map_json
          # Очищаем старую сборку
          rm -rf build
          mkdir build && cd build
          # Устанавливаем зависимости через Conan
          conan install .. --output-folder=. --build=missing
          # Конфигурируем проект
          cmake ..
          # Собираем проект
          make

      - name: run tests sprint1 map_json
        run: |
          cd cpp-backend-tests-practicum/scripts/sprint1
          ./map_json/run.sh

      - name: Publish XML reports
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          junit_files: ${{ github.workspace }}/*.xml

  sprint_3_flamegraph:
    if: github.repository_owner != 'cpppracticum'
    runs-on: ubuntu-22.04
    steps:

      - name: Checkout code & tests
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install dependencies
        run: |
          pip uninstall conan -y
          pip install -U conan==1.59.0
          pip install -r requirements.txt

      - name: Build map_json binary
        run: |
          ./cpp-backend-tests-practicum/scripts/sprint1/map_json/build.sh

      - name: Load FlameGraph
        uses: actions/checkout@v3
        with:
          repository: 'brendangregg/FlameGraph'
          path: ${{ github.workspace }}/sprint3/problems/flamegraph/solution/FlameGraph

      - name: run tests sprint3 flamegraph
        run: |
          cd cpp-backend-tests-practicum/scripts/sprint3
          ./flamegraph/run.sh

      - name: Publish XML reports
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          junit_files: ${{ github.workspace }}/*.xml
